server:
  port: 8081
spring:
  application:
    name: account
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tcc_account?characterEncoding=utf-8
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
mybatis:
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#mybatis-plus:
#  mapper-locations: classpath:com/hengxing/account/mappers/*xml